### ISSUE TITLE
[Minor Bug] unifi app won't reconnect after disconecting controller

### ISSUE THREAD

**Issue by robiebab** [mnederlof/com.ubnt.unifi#17]
If the controller has been disconnected and connected again, the unifi app won't connect anymore.

steps to repeat
for -example upgrade unifi the controller
wait until it is back again
go to homey and see to it keeps reconnecting 

expected result
it would reconnect after a controller disconnect and reconnect.

result
it won't connect after the, this example upgrade (until i reboot the unifi app)

**Comment by elcomes** [comment]
Same problem here. Can be fixed by add a line to the driver.js Add after line 660: this.reconnecting = true;  Like, // Start a poller, to check the device status every 30 secs. this.pollIntervals.push(setInterval(() => { if (!this.initialized) return this._debug('There is no connection yet 1, please check your settings!'); this._debug(`Polling clients (every ${this.options.defaultPollInterval} secs)`); this.updateClientList(); this.reconnecting = true; // fix for auto reconnect }, this.options.defaultPollInterval * 1000))

**Comment by robiebab** [comment]
that seems to work, only missing thing was: this.updateClientList()    nice work :) hopefuly it wil be corrected :)
